### ISSUE TITLE
Ссылка

### ISSUE THREAD

**Issue by sniffkaa** [gdeMojChay/Aliexpress-parser-RUS#1]
Как должна выглядеть ссылка? можно пример?

**Comment by gdeMojChay** [comment]
Это может быть любая ссылка, которая ведёт на страницу AliExpress, будь то https://aliexpress.ru/item/ или http://ali.pub/ и подобные.
Как пример: http://ali.pub/3ir5i0

**Comment by sniffkaa** [comment]
> Это может быть любая ссылка, которая ведёт на страницу AliExpress, будь то https://aliexpress.ru/item/ или http://ali.pub/ и подобных.
> Как пример: http://ali.pub/3ir5i0

http://ali.pub/ вообще не пашет, а обычный item создает пустой документ

**Comment by gdeMojChay** [comment]
В скором времени я займусь решением данной проблемы. Вероятно проблема в использование библиотеки urllib.request.
Буду переписывать на библиотеки requests и BeautifulSoup4.

**Comment by gdeMojChay** [comment]
Здравствуйте, дошли руки переписать пару строк кода, пожалуйста, проверьте работоспособность программы.

**Comment by sniffkaa** [comment]
снова пустой файл, все библиотеки установлены

**Comment by gdeMojChay** [comment]
Напишите (или выложите на облачное хранилище файлом) ссылки, которые вы используете.

**Comment by sniffkaa** [comment]
Я беру в пример, ту ссылку которую вы привели: https://aliexpress.ru/item/32828685972.html
http://ali.pub/3ir5i0

**Comment by gdeMojChay** [comment]
Здравствуйте, сейчас всё должно работать, но возможны проблемы с полями "Имя" в случае отсутствия в файле names_urls.txt и "Ссылка картинки", с которой я пока что не знаю что делать.
